# GitHub

- name: "bug"
  color: "D73A4A"
  description: "Something isn't working"

- name: "duplicate"
  color: "CFD3D7"
  description: "This issue or pull request already exists"

- name: "enhancement"
  color: "A2EEEF"
  description: "New feature or request"

- name: "good first issue"
  color: "7057FF"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "invalid"
  color: "E4E669"
  description: "This doesn't seem right"

- name: "repository"
  color: "C2E0C6"
  description: "Improves or adds to the repository"


# Renovate

- name: "dependencies"
  color: "0366D6"
  description: "Updates one or more dependencies"

- name: "auto-merge"
  color: "10A631"
  description: "Bot auto-merges"

- name: "stop-updating"
  color: "B60205"
  description: "Bot stops updating"
