services:
  bot:
    build: .
    restart: always
    environment:
      - CLIENT_TOKEN=$CLIENT_TOKEN
      - WORKER_TOKENS=$WORKER_TOKENS
      - DATABASE_URI=mongodb://db
      - OWNER_ID=$OWNER_ID
      - THEME_COLOR=$THEME_COLOR
      - AREA_LIMIT_PER_USER=$AREA_LIMIT_PER_USER
      - DISABLE_FUNNY_WORKER_NAMES=$DISABLE_FUNNY_WORKER_NAMES
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:8
    restart: always
    volumes:
      - ./database:/data/db
