version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_TOKEN=$CLIENT_TOKEN
      - WORKER_TOKENS=$WORKER_TOKENS
      - DATABASE_URI=mongodb://db
      - OWNER_ID=$OWNER_ID
      - THEME_COLOR=$THEME_COLOR
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:f0464afbae52b5b4a5fe253d2ec12e6422a60f3deb7d86fb7d9502a1f7a31b7d
    restart: always
    volumes:
      - ./database:/data/db
