version: '3'

services:
  bot:
    build: .
    restart: always
    environment:
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_TOKEN=$CLIENT_TOKEN
      - WORKER_TOKENS=$WORKER_TOKENS
      - DATABASE_URI=mongodb://db
      - OWNER_ID=$OWNER_ID
      - THEME_COLOR=$THEME_COLOR
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
  db:
    image: mongo:4@sha256:a98d30707edecfa5d1f04ba199731967d989ebe23aa2149d0a0005bd6de1c1c3
    restart: always
    volumes:
      - ./database:/data/db
