version: '3.8'

services:
  code:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye@sha256:93d647c8e067cf91f0e8d3a6a02ad4415af394eeec4c4c2fe7793bdfa6583b97
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: mongo:4@sha256:77afcc931f3035e5ee9bb3d456013274d3a3c9edd358e28ded7bafdedaf173ee
    restart: unless-stopped
    volumes:
      - ../database:/data/db
