version: '3.8'

services:
  code:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye@sha256:865bf56bee9daca016b6feafe918ced9cf83801c75710a25cd7c505d9f857323
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
  db:
    image: mongo:4@sha256:2712bd291a3d1e1534aef34ab5518b79845fb27bc325d2b912633f586ac9a523
    restart: unless-stopped
    volumes:
      - ../database:/data/db
